version: '3.8'

services:

  rabbitmq:
    build:
      context: ./
      dockerfile: Dockerfile
    hostname: docker-rabbitmq
    volumes:
      - "rabbitmq:/var/lib/rabbitmq/mnesia"
    ports:
      - '5672:5672'
      - '15672:15672'

volumes:
  rabbitmq:
